### ISSUE TITLE
Add support for the DISABLE_SERVER_SIDE_CURSORS setting

### ISSUE THREAD

**Issue by codeadict** [jacobian/dj-database-url#106]
To allow that the use of `DISABLE_SERVER_SIDE_CURSORS` setting (added in Django 1.11.1). See https://docs.djangoproject.com/en/2.0/ref/settings/#disable-server-side-cursors for reference.

**Comment by jacobian** [comment]
As with #117, I can't see an elegant way of doing this, so I'm closing. If you figure something out, let's move it over to #117 and re-open, since it's a general thing.
