### ISSUE TITLE
Request for Ownership Transfer

### ISSUE THREAD

**Issue by ParthS007** [jacobian/dj-database-url#119]
Hello @kennethreitz

I am using it many of my Django projects and I want to maintain it to take it forward.

Can you please transfer me this project?

I have added my comment [here](https://github.com/not-kennethreitz/team/issues/21#issuecomment-512670412)

**Comment by kennethreitz** [comment]
I have asked the DSF if they are interested, first. This is an extremely important project.

**Comment by kennethreitz** [comment]
Will also ask Heroku, potentially.

**Comment by ParthS007** [comment]
Okay @kennethreitz , Sounds Good :+1:

**Comment by kennethreitz** [comment]
This project is now owned by @jacobian, who will move it into django, at an appropriate time.

**Comment by jacobian** [comment]
Hey @ParthS007 thanks for the offer! There's definitely still room for others to help out if you're still interested, please see #120.
