### ISSUE TITLE
QUESTION: Django and Python version support

### ISSUE THREAD

**Issue by manishkpatel** [jacobian/dj-database-url#128]
To the contributors:

Hi,

Could you let me know which Django versions are supported by the `dj-database-url` plugin? We are trying to upgrade to Django 2.2 (_3.0.1 if possible_).

Apologies if this information is already out there - I searched on PyPi and the documentation on the landing page for this project, but could not find it.

Also, the PyPi page for this shows Python 3.5 as the highest supported version. Is this correct, or can we use a higher version of Python with this? We are trying to upgrade to Python 3.7 (_3.8 if possible_).

Regards,
  _Manish Patel_

**Comment by jacobian** [comment]
This supports Python > 2.7, and Django > 1.11 (and I've just added some better CI to verify that I'm right about that).

**Comment by manishkpatel** [comment]
> 
> 
> This supports Python > 2.7, and Django > 1.11 (and I've just added some better CI to verify that I'm right about that).

Thanks a lot for the clarification!
