### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by avorio** [jacobian/dj-database-url#62]
Where is the project's changelog kept, please?

I couldn't find an overview of changes from 0.3.0 to 0.4.0.

**Comment by olivierlefloch** [comment]
It would indeed be great to get a Changelog! For convenience, you could read the diff:

https://github.com/kennethreitz/dj-database-url/compare/v0.3.0...v0.4.0

Here are some changes that I noticed:

  - Oracle support was added
  - mysql-connector support was added
  - Special characters are now supported in user, password and name fields
  - conn_max_age support added
  - Database options are now parsed from the url
  - Python 3 support has either been added or improved

**Comment by avorio** [comment]
Thank you, @olivierlefloch!

**Comment by kennethreitz** [comment]
Anyone want to send a PR?

**Comment by adrienbrunet** [comment]
Here is mine 1 year after. See PR #111
